development:
  host: localhost
  port: 6379
  database: 0
  namespace: '/danthes'
test:
  host: localhost
  port: 6379
  database: 1
  namespace: '/danthes'
production:
  host: redis_host
  port: redis_port
  password: redis_password
  database: redis_database
  namespace: '/namespace'